#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mywebsite
#    username: burakyapici
#    password: Bfp711g+
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      show-sql: true
#
#security:
#  jwt:
#    secret: ${Y!V4aZ_U!^a|N1Q}
#


spring:
  datasource:
    url: jdbc:mysql://localhost/mywebsite
    username: burakyapici
    password: Bfp711g+
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

security:
  jwt:
    secret: ${Y!V4aZ_U!^a|N1Q}