spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mywebsite
    username: burakyapici
    password: Bfp711g+
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    cors:
      allowed-origins: "http://localhost:3000"

security:
  jwt:
    secret: ${Y!V4aZ_U!^a|N1Q}